# Generated by Django 4.1.3 on 2022-11-14 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CB_Driver_Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Driver_Name', models.CharField(blank=True, max_length=100)),
                ('Driver_ID', models.IntegerField(blank=True)),
                ('Email', models.CharField(blank=True, max_length=255)),
                ('Address', models.CharField(blank=True, max_length=255)),
                ('Active', models.SmallIntegerField(blank=True, default=0)),
            ],
            options={
                'db_table': 'CB_Driver_Master',
            },
        ),
    ]
