# Generated by Django 4.1.3 on 2022-11-14 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cb_driver_master',
            name='id',
        ),
        migrations.AddField(
            model_name='cb_driver_master',
            name='Mobile',
            field=models.IntegerField(blank=True, default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cb_driver_master',
            name='Driver_ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
