# Generated by Django 4.1.3 on 2022-11-14 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0003_alter_cb_driver_master_mobile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CB_Driver_Master',
        ),
    ]
