# Generated by Django 4.1.3 on 2022-11-14 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administration', '0004_delete_cb_driver_master'),
    ]

    operations = [
        migrations.CreateModel(
            name='CB_Driver_Master',
            fields=[
                ('Driver_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Driver_Name', models.CharField(blank=True, max_length=100)),
                ('Mobile', models.IntegerField(blank=True, default='')),
                ('Email', models.CharField(blank=True, max_length=255)),
                ('Address', models.CharField(blank=True, max_length=255)),
                ('Active', models.SmallIntegerField(blank=True, default=0)),
            ],
            options={
                'db_table': 'CB_Driver_Master',
            },
        ),
    ]
