# Generated by Django 4.1.2 on 2022-10-18 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ajsn_time_range',
            table='AJSN_time_range',
        ),
    ]
