# Generated by Django 4.1.2 on 2022-10-18 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_ajsn_time_range_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AJSN_tIme_range',
            new_name='AJSN_timeRange',
        ),
        migrations.AlterModelTable(
            name='ajsn_timerange',
            table='AJSN_timeRange',
        ),
    ]
