# Generated by Django 4.1.2 on 2022-10-22 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_at_transaction_delete_ajsn_timerange'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='at_transaction',
            table=None,
        ),
    ]
