# Generated by Django 4.1.2 on 2022-10-24 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_at_transaction_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='at_transaction',
            name='username',
            field=models.TextField(max_length=255),
        ),
    ]
