# Generated by Django 4.1.2 on 2022-10-24 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_at_transaction_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AT_transaction',
        ),
    ]
