# Generated by Django 4.1.2 on 2022-10-24 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='at_transaction',
            table='AT_transaction',
        ),
    ]
