# Generated by Django 4.1.2 on 2022-10-24 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AT_transaction',
            new_name='ajsn_transactions',
        ),
        migrations.AlterModelTable(
            name='ajsn_transactions',
            table='ajsn_transactions',
        ),
    ]
