# Generated by Django 4.1.2 on 2022-10-24 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_rename_at_transaction_ajsn_transactions_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ajsn_transactions',
        ),
    ]
