# Generated by Django 4.1.2 on 2022-10-24 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ajsn_transactions',
        ),
    ]
