# Generated by Django 4.1.2 on 2022-10-24 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_user_transactions_delete_ajsn_transactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_transactions',
            name='from_time',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='user_transactions',
            name='to_time',
            field=models.TextField(max_length=1000),
        ),
    ]
