# Generated by Django 4.1.2 on 2022-10-25 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_alter_user_transactions_from_time_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user_transactions',
            new_name='AT_transactions',
        ),
        migrations.AlterModelTable(
            name='at_transactions',
            table='AT_transactions',
        ),
    ]
