# Generated by Django 4.1.2 on 2022-10-26 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_rename_user_transactions_at_transactions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CB_Trans_Table',
            fields=[
                ('CB_Trans_Id', models.AutoField(primary_key=True, serialize=False)),
                ('dt', models.DateField()),
                ('UserId', models.TextField(max_length=8)),
                ('CB_For_ID', models.IntegerField()),
                ('No_Of_Passenger', models.IntegerField()),
                ('Source', models.TextField(max_length=250)),
                ('Destination', models.TextField(max_length=250)),
                ('Purpose', models.TextField(max_length=250)),
                ('Time_From', models.TimeField(max_length=6)),
                ('Time_To', models.TimeField(max_length=6)),
                ('Actual_Time_To', models.TimeField(max_length=6)),
                ('CBStatus', models.TextField(max_length=20)),
                ('CarId', models.IntegerField()),
                ('Driver_ID', models.IntegerField()),
                ('StartKm', models.IntegerField()),
                ('EndKm', models.IntegerField()),
                ('TotalKmTravelled', models.IntegerField()),
                ('Estimated_Amt', models.FloatField()),
                ('Actual_Amt', models.FloatField()),
                ('Payment_ID', models.IntegerField()),
                ('Payment_Ref_Id', models.IntegerField()),
                ('Payment_Status', models.TextField(max_length=15)),
                ('Submitted_By', models.TextField(max_length=8)),
                ('Overtime', models.SmallIntegerField(max_length=6)),
                ('Overtime_Time', models.TimeField(max_length=6)),
                ('TimeStamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'CB_Trans_Table',
            },
        ),
        migrations.DeleteModel(
            name='AT_transactions',
        ),
    ]
