# Generated by Django 4.1.2 on 2022-10-26 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_cb_trans_table_delete_at_transactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cb_trans_table',
            name='Overtime',
            field=models.SmallIntegerField(),
        ),
    ]
