# Generated by Django 4.1.2 on 2022-10-26 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_alter_cb_trans_table_overtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='CB_Option_Master',
            fields=[
                ('CB_For_Id', models.AutoField(primary_key=True, serialize=False)),
                ('CB_For', models.TextField(max_length=20)),
            ],
            options={
                'db_table': 'CB_Option_Master',
            },
        ),
    ]
