# Generated by Django 4.1.2 on 2022-10-26 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_cb_option_master'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cb_option_master',
            name='CB_For',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='cb_trans_table',
            name='CBStatus',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='cb_trans_table',
            name='Destination',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='cb_trans_table',
            name='Payment_Status',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='cb_trans_table',
            name='Purpose',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='cb_trans_table',
            name='Source',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='cb_trans_table',
            name='Submitted_By',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='cb_trans_table',
            name='UserId',
            field=models.CharField(max_length=8),
        ),
    ]
