# Generated by Django 4.1.2 on 2022-10-27 14:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_alter_cb_option_master_cb_for_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cb_trans_table',
            name='TimeStamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
