# Generated by Django 4.1.2 on 2022-10-27 15:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_alter_cb_trans_table_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cb_trans_table',
            name='Actual_Amt',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='cb_trans_table',
            name='Actual_Time_To',
            field=models.TimeField(blank=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='cb_trans_table',
            name='CBStatus',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='cb_trans_table',
            name='CB_For_ID',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='cb_trans_table',
            name='CarId',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='cb_trans_table',
            name='Driver_ID',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='cb_trans_table',
            name='EndKm',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='cb_trans_table',
            name='Estimated_Amt',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='cb_trans_table',
            name='No_Of_Passenger',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='cb_trans_table',
            name='Overtime',
            field=models.SmallIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='cb_trans_table',
            name='Overtime_Time',
            field=models.TimeField(blank=True, max_length=6),
        ),
        migrations.AlterField(
            model_name='cb_trans_table',
            name='Payment_ID',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='cb_trans_table',
            name='Payment_Ref_Id',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='cb_trans_table',
            name='Payment_Status',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='cb_trans_table',
            name='StartKm',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='cb_trans_table',
            name='Submitted_By',
            field=models.CharField(blank=True, max_length=8),
        ),
        migrations.AlterField(
            model_name='cb_trans_table',
            name='TimeStamp',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='cb_trans_table',
            name='TotalKmTravelled',
            field=models.IntegerField(blank=True),
        ),
    ]
