# Generated by Django 4.1.2 on 2022-10-27 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_alter_cb_trans_table_actual_amt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cb_trans_table',
            name='CB_For_ID',
            field=models.CharField(blank=True, max_length=1),
        ),
        migrations.AlterField(
            model_name='cb_trans_table',
            name='Overtime',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
