# Generated by Django 4.1.2 on 2022-10-27 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0026_alter_cb_trans_table_cb_for_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cb_trans_table',
            name='Overtime',
            field=models.SmallIntegerField(blank=True, default=1),
        ),
    ]
