# Generated by Django 4.1.2 on 2022-10-27 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_alter_cb_trans_table_cb_for_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cb_option_master',
            old_name='CB_For_Id',
            new_name='CB_For_ID',
        ),
    ]
