# Generated by Django 4.1.2 on 2022-10-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0031_alter_cb_trans_table_overtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cb_trans_table',
            name='Overtime',
            field=models.SmallIntegerField(blank=True, default=0),
        ),
    ]
